#!/usr/bin/env bash
#
# Configuration file for socketSink
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    #HEX_CAPITAL radio "" "Hexadecimal representation; 0: lower case; 1: upper case"
    #IP4_NORMALIZE check "" "Normalize IP addresses (zero padded to 3 digits)"
    #IP6_COMPRESS check "" "Compress IPv6 addresses"
    #TFS_EXTENDED_HEADER check "" "Extended header in flow file"
    #B2T_TIME_IN_MICRO_SECS radio "" "Time representation; 0: nanoseconds, 1: microseconds"
    #HDR_CHR text "" "Start character of comments"
    #SEP_CHR char "" "Character to use to separate the columns in the flow file"
    SERVADD text "" "Destination address"
    DPORT range "" "Destination port: 1 65535"
    SOCKTYPE radio "" "Socket type; UDP: UDP; TCP: TCP"
    GZ_COMPRESS check "SOCKTYPE == 1" "Compress the output using gzip"
    CONTENT_TYPE radio "" "Sent data; 0: binary; 1: text; 2: json"
    HOST_INFO check "CONTENT_TYPE == 1" "Print information about host"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
