#!/usr/bin/env bash
#
# Configuration file for popDecode
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    POP_SAVE check "" "Save content to POP_F_PATH"

    MXNMLN range "" "Maximal name length: 0 255"
    MXUNM  range "" "Maximal number of users: 0 255"
    MXPNM  range "" "Maximal number of passwords/parameters: 0 255"
    MXCNM  range "" "Maximal number of content: 0 255"

    POP_F_PATH text "POP_SAVE == 1" "Path for emails"
    POP_NON    text "POP_SAVE == 1" "No name file name"

    #POP_CNT_LEN    13 // max # of cnt digits attached to file name (currently not used).
    #POP_FNDX_LEN   20 // string length of findex in decimal format
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
