#!/usr/bin/env bash
#
# Configuration file for regex_pcre
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    EXPERTMODE radio "" "; \
            0: only display the most severe class; \
            1: display all matched classes plus some extra information"
    PKTTIME    check "" "Display the time at which a rule was matched"
    LABELSCANS check "" "Label scans (require tcpFlags plugin)"
    MAXREGPOS  range "" "Maximal # of matches stored / flow: 0 255"
    REXPOSIX_FILE text "" "Name of the regex file"
    RULE_OPTIMIZE check "" "Allocate opt rule structure & compile regex"
    #REGEX_MODE radio "" "Regex compile time options; PCRE_DOTALL"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
