#!/usr/bin/env bash
#
# Configuration file for dhcpDecode
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    DHCPBITFLD radio ""
        "DHCP options representation; \
            0: Option numbers in a row; \
            1: Bitfield"

    DHCPMAXOPT range "DHCPBITFLD == 0" "Maximum stored options: 0 255"

    DHCPNMMAX range "" "Maximal number of domain/host names per flow: 0 255"

    DHCPMASKFRMT radio ""
        "Netmask representation; \
            0: Hexadecimal; \
            1: IP address"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
