#!/usr/bin/env bash
#
# Configuration file for ircDecode
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    IRC_SAVE check "" "Save content to IRC_F_PATH"
    IRC_BITFIELD check "" "Bitfield coding of IRC commands"

    IRC_UXNMLN range "" "Maximal USER length: 0 255"
    IRC_PXNMLN range "" "Maximal PW length: 0 255"
    IRC_MXNMLN range "" "Maximal PW length: 0 255"

    IRC_MAXUNM range "" "Maximal number of users: 0 255"
    IRC_MAXPNM range "" "Maximal number of passwords: 0 255"
    IRC_MAXCNM range "" "Maximal number of parameters: 0 255"

    IRC_NON text "IRC_SAVE == 1" "No name file name"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
