#!/usr/bin/env bash
#
# Configuration file for ospfDecode
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    OSPF_OUTPUT_DBD check "" "Output routing tables"
    OSPF_OUTPUT_MSG check "" "Output all messages"

    OSPF_MASK_AS_IP radio ""
        "Netmask representation; \
            0: Hexadecimal; \
            1: IP address"

    OSPF_AREA_AS_IP radio ""
        "Areas representation; \
            0: Int; \
            1: IP; \
            2: Hex"

    OSPF_SUFFIX       text "" "Suffix for output file (statistics)"
    OSPF_HELLO_SUFFIX text "" "Suffix for output file (hello messages)"

    OSPF_DBD_SUFFIX   text "OSPF_OUTPUT_DBD == 1"
        "Suffix for output file (database description/routing tables)"

    OSPF_MSG_SUFFIX   text "OSPF_OUTPUT_MSG == 1"
        "Suffix for output file (All other messages from OSPF (Link State Request/Update/Ack))"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
