#!/usr/bin/env awk
#
# Returns true if one of the destination MAC addresses is equal to 'mac'
# If 'mac' is omitted, returns the destination MAC address(es)
#
# Dependencies:
#   - macRecorder
#
# See Also:
#   - dmac: alias for dether
#   - ether
#   - mac
#   - sether
#   - smac
#
# Examples:
#   - tawk 'dether("00:11:22:33:44:55")' file.txt
#   - tawk '{ print dether() }' file.txt

@include "dmac"

function dether(m) {
    return dmac(m)
}
