#!/usr/bin/env awk
#
# Returns true if the protocol number is equal to 47 (GRE)
#
# Parameters:
#   - [p] : the protocol to test [default: $l4Proto]
#
# Dependencies:
#   - basicFlow
#
# See Also:
#   - proto
#
# Examples:
#   - tawk 'gre()' file.txt
#   - tawk 'gre() { print $srcIP4 }' file.txt
#   - tawk 'gre($l4Proto)' file.txt
#   - tawk 'gre($l4Proto) { print $srcIP4 }' file.txt

@include "hdr"
@include "proto"

function gre(p) {
    if (hdr()) return __PRIHDR__
    if (p) return p == 47
    else return proto(47)
}
