#!/usr/bin/env awk
#
# Returns true if val finishes with the suffix 'suf' (case insensitive)
#
# Dependencies:
#   - None
#
# See Also:
#   - hasprefix
#   - hasprefixi
#   - hassuffix
#
# Examples:
#   - tawk 'hassuffixi($srcIP4, "255")' file.txt
#   - tawk 'hassuffixi("facebook", "BOOK") { print }' file.txt

@include "hassuffix"

function hassuffixi(val, suf) {
    return hassuffix(val, suf, 1)
}
