#!/usr/bin/env awk
#
# Compresses an IPv6 address
#
# Parameters:
#   - ip: the IPv6 to compress
#
# Dependencies:
#   - None
#
# See Also:
#   - ip6expand
#
# Examples:
#   - tawk '{ print ip6compress($srcIP6) }' file.txt

function ip6compress(ip) {
    ip = tolower(ip)
    sub(/(^|:)(0+(:|$)){2,8}/, "::", ip)
    ip = gensub(/(^|:)0+([0-9a-f])/, "\\1\\2", "g", ip)
    return ip
}
