#!/usr/bin/env awk
#
# Returns the mininum value between a, b and c
#
# Dependencies:
#   - None
#
# See Also:
#   - min
#   - min2
#   - max
#   - max2
#   - max3
#
# Examples:
#   - tawk '{ print min3(1, 2, 3) }' file.txt

function min3(a, b, c) {
    return (a < b ? (a < c ? a : c) : (b < c ? b : c))
}
