#!/usr/bin/env awk
#
# Returns true if one of the source MAC addresses is equal to 'mac'
# If 'mac' is omitted, returns the source MAC address(es)
#
# Dependencies:
#   - macRecorder
#
# See Also:
#   - dether
#   - dmac
#   - ether
#   - mac
#   - smac: alias for sether
#
# Examples:
#   - tawk 'sether("00:11:22:33:44:55")' file.txt
#   - tawk '{ print sether() }' file.txt

@include "smac"

function sether(m) {
    return smac(m)
}
