#!/usr/bin/env awk
#
# Removes leading and trailing quotes from a string 's'
#
# Dependencies:
#   - None
#
# Examples:
#   - tawk '{ print unquote($pwxUser) }' file.txt

function unquote(s) {
    if (s ~ /^"/) s = substr(s, 2)
    if (s ~ /"$/) s = substr(s, 1, length(s)-1)
    return s
}
