#!/usr/bin/env bash
#
# Configuration file for t2PSkel
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    MR_MAC_FMT radio ""
        "Format for MAC addresses; \
            0: hexadecimal; \
            1: MAC address (string); \
            2: integer"

    MR_NPAIRS check ""
        "Report number of distinct MAC addresses pairs"

    MR_MANUF radio ""
        "Representation of manufacturers; \
            0: no manufacturers; \
            1: short names; \
            2: long names"

    MR_MANUF_FILE text "MR_MANUF > 0" "Manufacturers file"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
