#!/usr/bin/env awk

hdr() {
    next
}

bitsallset($arpStat, 0x80) {
    _l = split($MAC_IP_cnt, _d, ";")
    for (_i = 1; _i <= _l; _i++) {
        split(_d[_i], _m, "_")
        print _m[1] OFS _m[2]
    }
}
