#!/usr/bin/env awk

hdr() {
    next
}

$dnsQname ~ /\./ && !bitsanyset($dnsStat, 0x12) {  # Ignore NBNS and truncated entries
    _l = split(tolower($dnsQname), _d, "\";\"")
    gsub(/^"/, "", _d[1])  # remove leading quote
    gsub(/"$/, "", _d[_l]) # remove trailing quote
    for (_i = 1; _i <= _l; _i++) {
        if (_d[_i] ~ /[^\.]\.[^\.]{2,}$/ && !isipstr(_d[_i])) {
            gsub(/^.+\./, "", _d[_i]);
            aggr(chomp(_d[_i]), "flows", n)
        }
    }
}
