#!/usr/bin/env bash
#
# Configuration file for voipDetector
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    VOIP_ANALEN check "" "Additional check report len against payload length"
    VOIP_V_SAVE check "" "Save RTP content"
    SIPNMMAX    range "" "Maximal SIP caller name length: 0 255"
    VOIP_RM_DIR check "VOIP_V_SAVE == 1" "Remove RTP content directory"
    VOIP_PLDOFF range "VOIP_V_SAVE == 1" "Offset for payload to be saved: 0 255"
    VOIP_V_PATH text  "VOIP_V_SAVE == 1" "Path for raw VoIP"
    VOIP_FNAME  text  "VOIP_V_SAVE == 1" "Default content file name prefix"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
