/*
* This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*/

#ifndef _NETFLOW_IPFIX_H
#define _NETFLOW_IPFIX_H

// ipfix element defines

#define IPFIX_octetDeltaCount                       0x0100
#define IPFIX_packetDeltaCount                      0x0200
#define IPFIX_deltaFlowCount                        0x0300
#define IPFIX_protocolIdentifier                    0x0400
#define IPFIX_ipClassOfService                      0x0500
#define IPFIX_tcpControlBits                        0x0600
#define IPFIX_sourceTransportPort                   0x0700
#define IPFIX_sourceIPv4Address                     0x0800
#define IPFIX_sourceIPv4PrefixLength                0x0900
#define IPFIX_ingressInterface                      0x0a00
#define IPFIX_destinationTransportPort              0x0b00
#define IPFIX_destinationIPv4Address                0x0c00
#define IPFIX_destinationIPv4PrefixLength           0x0d00
#define IPFIX_egressInterface                       0x0e00
#define IPFIX_ipNextHopIPv4Address                  0x0f00
#define IPFIX_bgpSourceAsNumber                     0x1000
#define IPFIX_bgpDestinationAsNumber                0x1100
#define IPFIX_bgpNextHopIPv4Address                 0x1200
#define IPFIX_postMCastPacketDeltaCount             0x1300
#define IPFIX_postMCastOctetDeltaCount              0x1400
#define IPFIX_flowEndSysUpTime                      0x1500
#define IPFIX_flowStartSysUpTime                    0x1600
#define IPFIX_postOctetDeltaCount                   0x1700
#define IPFIX_postPacketDeltaCount                  0x1800
#define IPFIX_minimumIpTotalLength                  0x1900
#define IPFIX_maximumIpTotalLength                  0x1a00
#define IPFIX_sourceIPv6Address                     0x1b00
#define IPFIX_destinationIPv6Address                0x1c00
#define IPFIX_sourceIPv6PrefixLength                0x1d00
#define IPFIX_destinationIPv6PrefixLength           0x1e00
#define IPFIX_flowLabelIPv6                         0x1f00
#define IPFIX_icmpTypeCodeIPv4                      0x2000
#define IPFIX_igmpType                              0x2100
#define IPFIX_samplingInterval                      0x2200
#define IPFIX_samplingAlgorithm                     0x2300
#define IPFIX_flowActiveTimeout                     0x2400
#define IPFIX_flowIdleTimeout                       0x2500
#define IPFIX_engineType                            0x2600
#define IPFIX_engineId                              0x2700
#define IPFIX_exportedOctetTotalCount               0x2800
#define IPFIX_exportedMessageTotalCount             0x2900
#define IPFIX_exportedFlowRecordTotalCount          0x2a00
#define IPFIX_ipv4RouterSc                          0x2b00
#define IPFIX_sourceIPv4Prefix                      0x2c00
#define IPFIX_destinationIPv4Prefix                 0x2d00
#define IPFIX_mplsTopLabelType                      0x2e00
#define IPFIX_mplsTopLabelIPv4Address               0x2f00
#define IPFIX_samplerId                             0x3000
#define IPFIX_samplerMode                           0x3100
#define IPFIX_samplerRandomInterval                 0x3200
#define IPFIX_classId                               0x3300
#define IPFIX_minimumTTL                            0x3400
#define IPFIX_maximumTTL                            0x3500
#define IPFIX_fragmentIdentification                0x3600
#define IPFIX_postIpClassOfService                  0x3700
#define IPFIX_sourceMacAddress                      0x3800
#define IPFIX_postDestinationMacAddress             0x3900
#define IPFIX_vlanId                                0x3a00
#define IPFIX_postVlanId                            0x3b00
#define IPFIX_ipVersion                             0x3c00
#define IPFIX_flowDirection                         0x3d00
#define IPFIX_ipNextHopIPv6Address                  0x3e00
#define IPFIX_bgpNextHopIPv6Address                 0x3f00
#define IPFIX_ipv6ExtensionHeaders                  0x4000
#define IPFIX_mplsTopLabelStackSection              0x4600
#define IPFIX_mplsLabelStackSection2                0x4700
#define IPFIX_mplsLabelStackSection3                0x4800
#define IPFIX_mplsLabelStackSection4                0x4900
#define IPFIX_mplsLabelStackSection5                0x4a00
#define IPFIX_mplsLabelStackSection6                0x4b00
#define IPFIX_mplsLabelStackSection7                0x4c00
#define IPFIX_mplsLabelStackSection8                0x4d00
#define IPFIX_mplsLabelStackSection9                0x4e00
#define IPFIX_mplsLabelStackSection10               0x4f00
#define IPFIX_destinationMacAddress                 0x5000
#define IPFIX_postSourceMacAddress                  0x5100
#define IPFIX_interfaceName                         0x5200
#define IPFIX_interfaceDescription                  0x5300
#define IPFIX_samplerName                           0x5400
#define IPFIX_octetTotalCount                       0x5500
#define IPFIX_packetTotalCount                      0x5600
#define IPFIX_flagsAndSamplerId                     0x5700
#define IPFIX_fragmentOffset                        0x5800
#define IPFIX_forwardingStatus                      0x5900
#define IPFIX_mplsVpnRouteDistinguisher             0x5a00
#define IPFIX_mplsTopLabelPrefixLength              0x5b00
#define IPFIX_srcTrafficIndex                       0x5c00
#define IPFIX_dstTrafficIndex                       0x5d00
#define IPFIX_applicationDescription                0x5e00
#define IPFIX_applicationId                         0x5f00
#define IPFIX_applicationName                       0x6000
#define IPFIX_postIpDiffServCodePoint               0x6200
#define IPFIX_multicastReplicationFactor            0x6300
#define IPFIX_className                             0x6400
#define IPFIX_classificationEngineId                0x6500
#define IPFIX_layer2packetSectionOffset             0x6600
#define IPFIX_layer2packetSectionSize               0x6700
#define IPFIX_layer2packetSectionData               0x6800
#define IPFIX_bgpNextAdjacentAsNumber               0x8000
#define IPFIX_bgpPrevAdjacentAsNumber               0x8100
#define IPFIX_exporterIPv4Address                   0x8200
#define IPFIX_exporterIPv6Address                   0x8300
#define IPFIX_droppedOctetDeltaCount                0x8400
#define IPFIX_droppedPacketDeltaCount               0x8500
#define IPFIX_droppedOctetTotalCount                0x8600
#define IPFIX_droppedPacketTotalCount               0x8700
#define IPFIX_flowEndReason                         0x8800
#define IPFIX_commonPropertiesId                    0x8900
#define IPFIX_observationPointId                    0x8a00
#define IPFIX_icmpTypeCodeIPv6                      0x8b00
#define IPFIX_mplsTopLabelIPv6Address               0x8c00
#define IPFIX_lineCardId                            0x8d00
#define IPFIX_portId                                0x8e00
#define IPFIX_meteringProcessId                     0x8f00
#define IPFIX_exportingProcessId                    0x9000
#define IPFIX_templateId                            0x9100
#define IPFIX_wlanChannelId                         0x9200
#define IPFIX_wlanSSID                              0x9300
#define IPFIX_flowId                                0x9400
#define IPFIX_observationDomainId                   0x9500
#define IPFIX_flowStartSeconds                      0x9600
#define IPFIX_flowEndSeconds                        0x9700
#define IPFIX_flowStartMilliseconds                 0x9800
#define IPFIX_flowEndMilliseconds                   0x9900
#define IPFIX_flowStartMicroseconds                 0x9a00
#define IPFIX_flowEndMicroseconds                   0x9b00
#define IPFIX_flowStartNanoseconds                  0x9c00
#define IPFIX_flowEndNanoseconds                    0x9d00
#define IPFIX_flowStartDeltaMicroseconds            0x9e00
#define IPFIX_flowEndDeltaMicroseconds              0x9f00
#define IPFIX_systemInitTimeMilliseconds            0xa000
#define IPFIX_flowDurationMilliseconds              0xa100
#define IPFIX_flowDurationMicroseconds              0xa200
#define IPFIX_observedFlowTotalCount                0xa300
#define IPFIX_ignoredPacketTotalCount               0xa400
#define IPFIX_ignoredOctetTotalCount                0xa500
#define IPFIX_notSentFlowTotalCount                 0xa600
#define IPFIX_notSentPacketTotalCount               0xa700
#define IPFIX_notSentOctetTotalCount                0xa800
#define IPFIX_destinationIPv6Prefix                 0xa900
#define IPFIX_sourceIPv6Prefix                      0xaa00
#define IPFIX_postOctetTotalCount                   0xab00
#define IPFIX_postPacketTotalCount                  0xac00
#define IPFIX_flowKeyIndicator                      0xad00
#define IPFIX_postMCastPacketTotalCount             0xae00
#define IPFIX_postMCastOctetTotalCount              0xaf00
#define IPFIX_icmpTypeIPv4                          0xb000
#define IPFIX_icmpCodeIPv4                          0xb100
#define IPFIX_icmpTypeIPv6                          0xb200
#define IPFIX_icmpCodeIPv6                          0xb300
#define IPFIX_udpSourcePort                         0xb400
#define IPFIX_udpDestinationPort                    0xb500
#define IPFIX_tcpSourcePort                         0xb600
#define IPFIX_tcpDestinationPort                    0xb700
#define IPFIX_tcpSequenceNumber                     0xb800
#define IPFIX_tcpAcknowledgementNumber              0xb900
#define IPFIX_tcpWindowSize                         0xba00
#define IPFIX_tcpUrgentPointer                      0xbb00
#define IPFIX_tcpHeaderLength                       0xbc00
#define IPFIX_ipHeaderLength                        0xbd00
#define IPFIX_totalLengthIPv4                       0xbe00
#define IPFIX_payloadLengthIPv6                     0xbf00
#define IPFIX_ipTTL                                 0xc000
#define IPFIX_nextHeaderIPv6                        0xc100
#define IPFIX_mplsPayloadLength                     0xc200
#define IPFIX_ipDiffServCodePoint                   0xc300
#define IPFIX_ipPrecedence                          0xc400
#define IPFIX_fragmentFlags                         0xc500
#define IPFIX_octetDeltaSumOfSquares                0xc600
#define IPFIX_octetTotalSumOfSquares                0xc700
#define IPFIX_mplsTopLabelTTL                       0xc800
#define IPFIX_mplsLabelStackLength                  0xc900
#define IPFIX_mplsLabelStackDepth                   0xca00
#define IPFIX_mplsTopLabelExp                       0xcb00
#define IPFIX_ipPayloadLength                       0xcc00
#define IPFIX_udpMessageLength                      0xcd00
#define IPFIX_isMulticast                           0xce00
#define IPFIX_ipv4IHL                               0xcf00
#define IPFIX_ipv4Options                           0xd000
#define IPFIX_tcpOptions                            0xd100
#define IPFIX_paddingOctets                         0xd200
#define IPFIX_collectorIPv4Address                  0xd300
#define IPFIX_collectorIPv6Address                  0xd400
#define IPFIX_exportInterface                       0xd500
#define IPFIX_exportProtocolVersion                 0xd600
#define IPFIX_exportTransportProtocol               0xd700
#define IPFIX_collectorTransportPort                0xd800
#define IPFIX_exporterTransportPort                 0xd900
#define IPFIX_tcpSynTotalCount                      0xda00
#define IPFIX_tcpFinTotalCount                      0xdb00
#define IPFIX_tcpRstTotalCount                      0xdc00
#define IPFIX_tcpPshTotalCount                      0xdd00
#define IPFIX_tcpAckTotalCount                      0xde00
#define IPFIX_tcpUrgTotalCount                      0xdf00
#define IPFIX_ipTotalLength                         0xe000
#define IPFIX_postNATSourceIPv4Address              0xe100
#define IPFIX_postNATDestinationIPv4Address         0xe200
#define IPFIX_postNAPTSourceTransportPort           0xe300
#define IPFIX_postNAPTDestinationTransportPort      0xe400
#define IPFIX_natOriginatingAddressRealm            0xe500
#define IPFIX_natEvent                              0xe600
#define IPFIX_initiatorOctets                       0xe700
#define IPFIX_responderOctets                       0xe800
#define IPFIX_firewallEvent                         0xe900
#define IPFIX_ingressVRFID                          0xea00
#define IPFIX_egressVRFID                           0xeb00
#define IPFIX_VRFname                               0xec00
#define IPFIX_postMplsTopLabelExp                   0xed00
#define IPFIX_tcpWindowScale                        0xee00
#define IPFIX_biflowDirection                       0xef00
#define IPFIX_ethernetHeaderLength                  0xf000
#define IPFIX_ethernetPayloadLength                 0xf100
#define IPFIX_ethernetTotalLength                   0xf200
#define IPFIX_dot1qVlanId                           0xf300
#define IPFIX_dot1qPriority                         0xf400
#define IPFIX_dot1qCustomerVlanId                   0xf500
#define IPFIX_dot1qCustomerPriority                 0xf600
#define IPFIX_metroEvcId                            0xf700
#define IPFIX_metroEvcType                          0xf800
#define IPFIX_pseudoWireId                          0xf900
#define IPFIX_pseudoWireType                        0xfa00
#define IPFIX_pseudoWireControlWord                 0xfb00
#define IPFIX_ingressPhysicalInterface              0xfc00
#define IPFIX_egressPhysicalInterface               0xfd00
#define IPFIX_postDot1qVlanId                       0xfe00
#define IPFIX_postDot1qCustomerVlanId               0xff00
#define IPFIX_ethernetType                          0x0001
#define IPFIX_postIpPrecedence                      0x0101
#define IPFIX_collectionTimeMilliseconds            0x0201
#define IPFIX_exportSctpStreamId                    0x0301
#define IPFIX_maxExportSeconds                      0x0401
#define IPFIX_maxFlowEndSeconds                     0x0501
#define IPFIX_messageMD5Checksum                    0x0601
#define IPFIX_messageScope                          0x0701
#define IPFIX_minExportSeconds                      0x0801
#define IPFIX_minFlowStartSeconds                   0x0901
#define IPFIX_opaqueOctets                          0x0a01
#define IPFIX_sessionScope                          0x0b01
#define IPFIX_maxFlowEndMicroseconds                0x0c01
#define IPFIX_maxFlowEndMilliseconds                0x0d01
#define IPFIX_maxFlowEndNanoseconds                 0x0e01
#define IPFIX_minFlowStartMicroseconds              0x0f01
#define IPFIX_minFlowStartMilliseconds              0x1001
#define IPFIX_minFlowStartNanoseconds               0x1101
#define IPFIX_collectorCertificate                  0x1201
#define IPFIX_exporterCertificate                   0x1301
#define IPFIX_dataRecordsReliability                0x1401
#define IPFIX_observationPointType                  0x1501
#define IPFIX_newConnectionDeltaCount               0x1601
#define IPFIX_connectionSumDurationSeconds          0x1701
#define IPFIX_connectionTransactionId               0x1801
#define IPFIX_postNATSourceIPv6Address              0x1901
#define IPFIX_postNATDestinationIPv6Address         0x1a01
#define IPFIX_natPoolId                             0x1b01
#define IPFIX_natPoolName                           0x1c01
#define IPFIX_anonymizationFlags                    0x1d01
#define IPFIX_anonymizationTechnique                0x1e01
#define IPFIX_informationElementIndex               0x1f01
#define IPFIX_p2pTechnology                         0x2001
#define IPFIX_tunnelTechnology                      0x2101
#define IPFIX_encryptedTechnology                   0x2201
#define IPFIX_basicList                             0x2301
#define IPFIX_subTemplateList                       0x2401
#define IPFIX_subTemplateMultiList                  0x2501
#define IPFIX_bgpValidityState                      0x2601
#define IPFIX_IPSecSPI                              0x2701
#define IPFIX_greKey                                0x2801
#define IPFIX_natType                               0x2901
#define IPFIX_initiatorPackets                      0x2a01
#define IPFIX_responderPackets                      0x2b01
#define IPFIX_observationDomainName                 0x2c01
#define IPFIX_selectionSequenceId                   0x2d01
#define IPFIX_selectorId                            0x2e01
#define IPFIX_informationElementId                  0x2f01
#define IPFIX_selectorAlgorithm                     0x3001
#define IPFIX_samplingPacketInterval                0x3101
#define IPFIX_samplingPacketSpace                   0x3201
#define IPFIX_samplingTimeInterval                  0x3301
#define IPFIX_samplingTimeSpace                     0x3401
#define IPFIX_samplingSize                          0x3501
#define IPFIX_samplingPopulation                    0x3601
#define IPFIX_samplingProbability                   0x3701
#define IPFIX_dataLinkFrameSize                     0x3801
#define IPFIX_ipHeaderPacketSection                 0x3901
#define IPFIX_ipPayloadPacketSection                0x3a01
#define IPFIX_dataLinkFrameSection                  0x3b01
#define IPFIX_mplsLabelStackSection                 0x3c01
#define IPFIX_mplsPayloadPacketSection              0x3d01
#define IPFIX_selectorIdTotalPktsObserved           0x3e01
#define IPFIX_selectorIdTotalPktsSelected           0x3f01
#define IPFIX_absoluteError                         0x4001
#define IPFIX_relativeError                         0x4101
#define IPFIX_observationTimeSeconds                0x4201
#define IPFIX_observationTimeMilliseconds           0x4301
#define IPFIX_observationTimeMicroseconds           0x4401
#define IPFIX_observationTimeNanoseconds            0x4501
#define IPFIX_digestHashValue                       0x4601
#define IPFIX_hashIPPayloadOffset                   0x4701
#define IPFIX_hashIPPayloadSize                     0x4801
#define IPFIX_hashOutputRangeMin                    0x4901
#define IPFIX_hashOutputRangeMax                    0x4a01
#define IPFIX_hashSelectedRangeMin                  0x4b01
#define IPFIX_hashSelectedRangeMax                  0x4c01
#define IPFIX_hashDigestOutput                      0x4d01
#define IPFIX_hashInitialiserValue                  0x4e01
#define IPFIX_selectorName                          0x4f01
#define IPFIX_upperCILimit                          0x5001
#define IPFIX_lowerCILimit                          0x5101
#define IPFIX_confidenceLevel                       0x5201
#define IPFIX_informationElementDataType            0x5301
#define IPFIX_informationElementDescription         0x5401
#define IPFIX_informationElementName                0x5501
#define IPFIX_informationElementRangeBegin          0x5601
#define IPFIX_informationElementRangeEnd            0x5701
#define IPFIX_informationElementSemantics           0x5801
#define IPFIX_informationElementUnits               0x5901
#define IPFIX_privateEnterpriseNumber               0x5a01
#define IPFIX_virtualStationInterfaceId             0x5b01
#define IPFIX_virtualStationInterfaceName           0x5c01
#define IPFIX_virtualStationUUID                    0x5d01
#define IPFIX_virtualStationName                    0x5e01
#define IPFIX_layer2SegmentId                       0x5f01
#define IPFIX_layer2OctetDeltaCount                 0x6001
#define IPFIX_layer2OctetTotalCount                 0x6101
#define IPFIX_ingressUnicastPacketTotalCount        0x6201
#define IPFIX_ingressMulticastPacketTotalCount      0x6301
#define IPFIX_ingressBroadcastPacketTotalCount      0x6401
#define IPFIX_egressUnicastPacketTotalCount         0x6501
#define IPFIX_egressBroadcastPacketTotalCount       0x6601
#define IPFIX_monitoringIntervalStartMilliSeconds   0x6701
#define IPFIX_monitoringIntervalEndMilliSeconds     0x6801
#define IPFIX_portRangeStart                        0x6901
#define IPFIX_portRangeEnd                          0x6a01
#define IPFIX_portRangeStepSize                     0x6b01
#define IPFIX_portRangeNumPorts                     0x6c01
#define IPFIX_staMacAddress                         0x6d01
#define IPFIX_staIPv4Address                        0x6e01
#define IPFIX_wtpMacAddress                         0x6f01
#define IPFIX_ingressInterfaceType                  0x7001
#define IPFIX_egressInterfaceType                   0x7101
#define IPFIX_rtpSequenceNumber                     0x7201
#define IPFIX_userName                              0x7301
#define IPFIX_applicationCategoryName               0x7401
#define IPFIX_applicationSubCategoryName            0x7501
#define IPFIX_applicationGroupName                  0x7601
#define IPFIX_originalFlowsPresent                  0x7701
#define IPFIX_originalFlowsInitiated                0x7801
#define IPFIX_originalFlowsCompleted                0x7901
#define IPFIX_distinctCountOfSourceIPAddress        0x7a01
#define IPFIX_distinctCountOfDestinationIPAddress   0x7b01
#define IPFIX_distinctCountOfSourceIPv4Address      0x7c01
#define IPFIX_distinctCountOfDestinationIPv4Address 0x7d01
#define IPFIX_distinctCountOfSourceIPv6Address      0x7e01
#define IPFIX_distinctCountOfDestinationIPv6Address 0x7f01
#define IPFIX_valueDistributionMethod               0x8001
#define IPFIX_rfc3550JitterMilliseconds             0x8101
#define IPFIX_rfc3550JitterMicroseconds             0x8201
#define IPFIX_rfc3550JitterNanoseconds              0x8301
#define IPFIX_dot1qDEI                              0x8401
#define IPFIX_dot1qCustomerDEI                      0x8501
#define IPFIX_flowSelectorAlgorithm                 0x8601
#define IPFIX_flowSelectedOctetDeltaCount           0x8701
#define IPFIX_flowSelectedPacketDeltaCount          0x8801
#define IPFIX_flowSelectedFlowDeltaCount            0x8901
#define IPFIX_selectorIDTotalFlowsObserved          0x8a01
#define IPFIX_selectorIDTotalFlowsSelected          0x8b01
#define IPFIX_samplingFlowInterval                  0x8c01
#define IPFIX_samplingFlowSpacing                   0x8d01
#define IPFIX_flowSamplingTimeInterval              0x8e01
#define IPFIX_flowSamplingTimeSpacing               0x8f01
#define IPFIX_hashFlowDomain                        0x9001
#define IPFIX_transportOctetDeltaCount              0x9101
#define IPFIX_transportPacketDeltaCount             0x9201
#define IPFIX_originalExporterIPv4Address           0x9301
#define IPFIX_originalExporterIPv6Address           0x9401
#define IPFIX_originalObservationDomainId           0x9501
#define IPFIX_intermediateProcessId                 0x9601
#define IPFIX_ignoredDataRecordTotalCount           0x9701
#define IPFIX_dataLinkFrameType                     0x9801
#define IPFIX_sectionOffset                         0x9901
#define IPFIX_sectionExportedOctets                 0x9a01
#define IPFIX_dot1qServiceInstanceTag               0x9b01
#define IPFIX_dot1qServiceInstanceId                0x9c01
#define IPFIX_dot1qServiceInstancePriority          0x9d01
#define IPFIX_dot1qCustomerSourceMacAddress         0x9e01
#define IPFIX_dot1qCustomerDestinationMacAddress    0x9f01
#define IPFIX_postLayer2OctetDeltaCount             0xa101
#define IPFIX_postMCastLayer2OctetDeltaCount        0xa201
#define IPFIX_postLayer2OctetTotalCount             0xa401
#define IPFIX_postMCastLayer2OctetTotalCount        0xa501
#define IPFIX_minimumLayer2TotalLength              0xa601
#define IPFIX_maximumLayer2TotalLength              0xa701
#define IPFIX_droppedLayer2OctetDeltaCount          0xa801
#define IPFIX_droppedLayer2OctetTotalCount          0xa901
#define IPFIX_ignoredLayer2OctetTotalCount          0xaa01
#define IPFIX_notSentLayer2OctetTotalCount          0xab01
#define IPFIX_layer2OctetDeltaSumOfSquares          0xac01
#define IPFIX_layer2OctetTotalSumOfSquares          0xad01
#define IPFIX_layer2FrameDeltaCount                 0xae01
#define IPFIX_layer2FrameTotalCount                 0xaf01
#define IPFIX_pseudoWireDestinationIPv4Address      0xb001
#define IPFIX_ignoredLayer2FrameTotalCount          0xb101

// length of ipfix fields

#define IPFIX_octetDeltaCount_LEN                       sizeof(uint64_t)
#define IPFIX_packetDeltaCount_LEN                      sizeof(uint64_t)
#define IPFIX_deltaFlowCount_LEN                        sizeof(uint64_t)
#define IPFIX_protocolIdentifier_LEN                    sizeof(uint8_t)
#define IPFIX_ipClassOfService_LEN                      sizeof(uint8_t)
#define IPFIX_tcpControlBits_LEN                        sizeof(uint16_t)
#define IPFIX_sourceTransportPort_LEN                   sizeof(uint16_t)
#define IPFIX_sourceIPv4Address_LEN                     sizeof(in_addr)
#define IPFIX_sourceIPv4PrefixLength_LEN                sizeof(uint8_t)
#define IPFIX_ingressInterface_LEN                      sizeof(uint32_t)
#define IPFIX_destinationTransportPort_LEN              sizeof(uint16_t)
#define IPFIX_destinationIPv4Address_LEN                sizeof(in_addr)
#define IPFIX_destinationIPv4PrefixLength_LEN           sizeof(uint8_t)
#define IPFIX_egressInterface_LEN                       sizeof(uint32_t)
#define IPFIX_ipNextHopIPv4Address_LEN                  sizeof(in_addr)
#define IPFIX_bgpSourceAsNumber_LEN                     sizeof(uint32_t)
#define IPFIX_bgpDestinationAsNumber_LEN                sizeof(uint32_t)
#define IPFIX_bgpNextHopIPv4Address_LEN                 sizeof(in_addr)
#define IPFIX_postMCastPacketDeltaCount_LEN             sizeof(uint64_t)
#define IPFIX_postMCastOctetDeltaCount_LEN              sizeof(uint64_t)
#define IPFIX_flowEndSysUpTime_LEN                      sizeof(uint32_t)
#define IPFIX_flowStartSysUpTime_LEN                    sizeof(uint32_t)
#define IPFIX_postOctetDeltaCount_LEN                   sizeof(uint64_t)
#define IPFIX_postPacketDeltaCount_LEN                  sizeof(uint64_t)
#define IPFIX_minimumIpTotalLength_LEN                  sizeof(uint64_t)
#define IPFIX_maximumIpTotalLength_LEN                  sizeof(uint64_t)
#define IPFIX_sourceIPv6Address_LEN                     sizeof(in6_addr)
#define IPFIX_destinationIPv6Address_LEN                sizeof(in6_addr)
#define IPFIX_sourceIPv6PrefixLength_LEN                sizeof(uint8_t)
#define IPFIX_destinationIPv6PrefixLength_LEN           sizeof(uint8_t)
#define IPFIX_flowLabelIPv6_LEN                         sizeof(uint32_t)
#define IPFIX_icmpTypeCodeIPv4_LEN                      sizeof(uint16_t)
#define IPFIX_igmpType_LEN                              sizeof(uint8_t)
#define IPFIX_samplingInterval_LEN                      sizeof(uint32_t)
#define IPFIX_samplingAlgorithm_LEN                     sizeof(uint8_t)
#define IPFIX_flowActiveTimeout_LEN                     sizeof(uint16_t)
#define IPFIX_flowIdleTimeout_LEN                       sizeof(uint16_t)
#define IPFIX_engineType_LEN                            sizeof(uint8_t)
#define IPFIX_engineId_LEN                              sizeof(uint8_t)
#define IPFIX_exportedOctetTotalCount_LEN               sizeof(uint64_t)
#define IPFIX_exportedMessageTotalCount_LEN             sizeof(uint64_t)
#define IPFIX_exportedFlowRecordTotalCount_LEN          sizeof(uint64_t)
#define IPFIX_ipv4RouterSc_LEN                          sizeof(in_addr)
#define IPFIX_sourceIPv4Prefix_LEN                      sizeof(in_addr)
#define IPFIX_destinationIPv4Prefix_LEN                 sizeof(in_addr)
#define IPFIX_mplsTopLabelType_LEN                      sizeof(uint8_t)
#define IPFIX_mplsTopLabelIPv4Address_LEN               sizeof(in_addr)
#define IPFIX_samplerId_LEN                             sizeof(uint8_t)
#define IPFIX_samplerMode_LEN                           sizeof(uint8_t)
#define IPFIX_samplerRandomInterval_LEN                 sizeof(uint32_t)
#define IPFIX_classId_LEN                               sizeof(uint8_t)
#define IPFIX_minimumTTL_LEN                            sizeof(uint8_t)
#define IPFIX_maximumTTL_LEN                            sizeof(uint8_t)
#define IPFIX_fragmentIdentification_LEN                sizeof(uint32_t)
#define IPFIX_postIpClassOfService_LEN                  sizeof(uint8_t)
#define IPFIX_sourceMacAddress_LEN                      ETH_ALEN
#define IPFIX_postDestinationMacAddress_LEN             ETH_ALEN
#define IPFIX_vlanId_LEN                                sizeof(uint16_t)
#define IPFIX_postVlanId_LEN                            sizeof(uint16_t)
#define IPFIX_ipVersion_LEN                             sizeof(uint8_t)
#define IPFIX_flowDirection_LEN                         sizeof(uint8_t)
#define IPFIX_ipNextHopIPv6Address_LEN                  sizeof(in6_addr)
#define IPFIX_bgpNextHopIPv6Address_LEN                 sizeof(in6_addr)
#define IPFIX_ipv6ExtensionHeaders_LEN                  sizeof(uint32_t)
#define IPFIX_mplsTopLabelStackSection_LEN              sizeof(octetArray)
#define IPFIX_mplsLabelStackSection2_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection3_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection4_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection5_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection6_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection7_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection8_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection9_LEN                sizeof(octetArray)
#define IPFIX_mplsLabelStackSection10_LEN               sizeof(octetArray)
#define IPFIX_destinationMacAddress_LEN                 ETH_ALEN
#define IPFIX_postSourceMacAddress_LEN                  ETH_ALEN
#define IPFIX_interfaceName_LEN                         sizeof(string)
#define IPFIX_interfaceDescription_LEN                  sizeof(string)
#define IPFIX_samplerName_LEN                           sizeof(string)
#define IPFIX_octetTotalCount_LEN                       sizeof(uint64_t)
#define IPFIX_packetTotalCount_LEN                      sizeof(uint64_t)
#define IPFIX_flagsAndSamplerId_LEN                     sizeof(uint32_t)
#define IPFIX_fragmentOffset_LEN                        sizeof(uint16_t)
#define IPFIX_forwardingStatus_LEN                      sizeof(uint32_t)
#define IPFIX_mplsVpnRouteDistinguisher_LEN             sizeof(octetArray)
#define IPFIX_mplsTopLabelPrefixLength_LEN              sizeof(uint8_t)
#define IPFIX_srcTrafficIndex_LEN                       sizeof(uint32_t)
#define IPFIX_dstTrafficIndex_LEN                       sizeof(uint32_t)
#define IPFIX_applicationDescription_LEN                sizeof(string)
#define IPFIX_applicationId_LEN                         sizeof(octetArray)
#define IPFIX_applicationName_LEN                       sizeof(string)
#define IPFIX_postIpDiffServCodePoint_LEN               sizeof(uint8_t)
#define IPFIX_multicastReplicationFactor_LEN            sizeof(uint32_t)
#define IPFIX_className_LEN                             sizeof(string)
#define IPFIX_classificationEngineId_LEN                sizeof(uint8_t)
#define IPFIX_layer2packetSectionOffset_LEN             sizeof(uint16_t)
#define IPFIX_layer2packetSectionSize_LEN               sizeof(uint16_t)
#define IPFIX_layer2packetSectionData_LEN               sizeof(octetArray)
#define IPFIX_bgpNextAdjacentAsNumber_LEN               sizeof(uint32_t)
#define IPFIX_bgpPrevAdjacentAsNumber_LEN               sizeof(uint32_t)
#define IPFIX_exporterIPv4Address_LEN                   sizeof(in_addr)
#define IPFIX_exporterIPv6Address_LEN                   sizeof(in6_addr)
#define IPFIX_droppedOctetDeltaCount_LEN                sizeof(uint64_t)
#define IPFIX_droppedPacketDeltaCount_LEN               sizeof(uint64_t)
#define IPFIX_droppedOctetTotalCount_LEN                sizeof(uint64_t)
#define IPFIX_droppedPacketTotalCount_LEN               sizeof(uint64_t)
#define IPFIX_flowEndReason_LEN                         sizeof(uint8_t)
#define IPFIX_commonPropertiesId_LEN                    sizeof(uint64_t)
#define IPFIX_observationPointId_LEN                    sizeof(uint64_t)
#define IPFIX_icmpTypeCodeIPv6_LEN                      sizeof(uint16_t)
#define IPFIX_mplsTopLabelIPv6Address_LEN               sizeof(in6_addr)
#define IPFIX_lineCardId_LEN                            sizeof(uint32_t)
#define IPFIX_portId_LEN                                sizeof(uint32_t)
#define IPFIX_meteringProcessId_LEN                     sizeof(uint32_t)
#define IPFIX_exportingProcessId_LEN                    sizeof(uint32_t)
#define IPFIX_templateId_LEN                            sizeof(uint16_t)
#define IPFIX_wlanChannelId_LEN                         sizeof(uint8_t)
#define IPFIX_wlanSSID_LEN                              sizeof(string)
#define IPFIX_flowId_LEN                                sizeof(uint64_t)
#define IPFIX_observationDomainId_LEN                   sizeof(uint32_t)
#define IPFIX_flowStartSeconds_LEN                      sizeof(dateTimeSeconds)
#define IPFIX_flowEndSeconds_LEN                        sizeof(dateTimeSeconds)
#define IPFIX_flowStartMilliseconds_LEN                 sizeof(dateTimeMilliseconds)
#define IPFIX_flowEndMilliseconds_LEN                   sizeof(dateTimeMilliseconds)
#define IPFIX_flowStartMicroseconds_LEN                 sizeof(dateTimeMicroseconds)
#define IPFIX_flowEndMicroseconds_LEN                   sizeof(dateTimeMicroseconds)
#define IPFIX_flowStartNanoseconds_LEN                  sizeof(dateTimeNanoseconds)
#define IPFIX_flowEndNanoseconds_LEN                    sizeof(dateTimeNanoseconds)
#define IPFIX_flowStartDeltaMicroseconds_LEN            sizeof(uint32_t)
#define IPFIX_flowEndDeltaMicroseconds_LEN              sizeof(uint32_t)
#define IPFIX_systemInitTimeMilliseconds_LEN            sizeof(dateTimeMilliseconds)
#define IPFIX_flowDurationMilliseconds_LEN              sizeof(uint32_t)
#define IPFIX_flowDurationMicroseconds_LEN              sizeof(uint32_t)
#define IPFIX_observedFlowTotalCount_LEN                sizeof(uint64_t)
#define IPFIX_ignoredPacketTotalCount_LEN               sizeof(uint64_t)
#define IPFIX_ignoredOctetTotalCount_LEN                sizeof(uint64_t)
#define IPFIX_notSentFlowTotalCount_LEN                 sizeof(uint64_t)
#define IPFIX_notSentPacketTotalCount_LEN               sizeof(uint64_t)
#define IPFIX_notSentOctetTotalCount_LEN                sizeof(uint64_t)
#define IPFIX_destinationIPv6Prefix_LEN                 sizeof(in6_addr)
#define IPFIX_sourceIPv6Prefix_LEN                      sizeof(in6_addr)
#define IPFIX_postOctetTotalCount_LEN                   sizeof(uint64_t)
#define IPFIX_postPacketTotalCount_LEN                  sizeof(uint64_t)
#define IPFIX_flowKeyIndicator_LEN                      sizeof(uint64_t)
#define IPFIX_postMCastPacketTotalCount_LEN             sizeof(uint64_t)
#define IPFIX_postMCastOctetTotalCount_LEN              sizeof(uint64_t)
#define IPFIX_icmpTypeIPv4_LEN                          sizeof(uint8_t)
#define IPFIX_icmpCodeIPv4_LEN                          sizeof(uint8_t)
#define IPFIX_icmpTypeIPv6_LEN                          sizeof(uint8_t)
#define IPFIX_icmpCodeIPv6_LEN                          sizeof(uint8_t)
#define IPFIX_udpSourcePort_LEN                         sizeof(uint16_t)
#define IPFIX_udpDestinationPort_LEN                    sizeof(uint16_t)
#define IPFIX_tcpSourcePort_LEN                         sizeof(uint16_t)
#define IPFIX_tcpDestinationPort_LEN                    sizeof(uint16_t)
#define IPFIX_tcpSequenceNumber_LEN                     sizeof(uint32_t)
#define IPFIX_tcpAcknowledgementNumber_LEN              sizeof(uint32_t)
#define IPFIX_tcpWindowSize_LEN                         sizeof(uint16_t)
#define IPFIX_tcpUrgentPointer_LEN                      sizeof(uint16_t)
#define IPFIX_tcpHeaderLength_LEN                       sizeof(uint8_t)
#define IPFIX_ipHeaderLength_LEN                        sizeof(uint8_t)
#define IPFIX_totalLengthIPv4_LEN                       sizeof(uint16_t)
#define IPFIX_payloadLengthIPv6_LEN                     sizeof(uint16_t)
#define IPFIX_ipTTL_LEN                                 sizeof(uint8_t)
#define IPFIX_nextHeaderIPv6_LEN                        sizeof(uint8_t)
#define IPFIX_mplsPayloadLength_LEN                     sizeof(uint32_t)
#define IPFIX_ipDiffServCodePoint_LEN                   sizeof(uint8_t)
#define IPFIX_ipPrecedence_LEN                          sizeof(uint8_t)
#define IPFIX_fragmentFlags_LEN                         sizeof(uint8_t)
#define IPFIX_octetDeltaSumOfSquares_LEN                sizeof(uint64_t)
#define IPFIX_octetTotalSumOfSquares_LEN                sizeof(uint64_t)
#define IPFIX_mplsTopLabelTTL_LEN                       sizeof(uint8_t)
#define IPFIX_mplsLabelStackLength_LEN                  sizeof(uint32_t)
#define IPFIX_mplsLabelStackDepth_LEN                   sizeof(uint32_t)
#define IPFIX_mplsTopLabelExp_LEN                       sizeof(uint8_t)
#define IPFIX_ipPayloadLength_LEN                       sizeof(uint32_t)
#define IPFIX_udpMessageLength_LEN                      sizeof(uint16_t)
#define IPFIX_isMulticast_LEN                           sizeof(uint8_t)
#define IPFIX_ipv4IHL_LEN                               sizeof(uint8_t)
#define IPFIX_ipv4Options_LEN                           sizeof(uint32_t)
#define IPFIX_tcpOptions_LEN                            sizeof(uint64_t)
#define IPFIX_paddingOctets_LEN                         sizeof(octetArray)
#define IPFIX_collectorIPv4Address_LEN                  sizeof(in_addr)
#define IPFIX_collectorIPv6Address_LEN                  sizeof(in6_addr)
#define IPFIX_exportInterface_LEN                       sizeof(uint32_t)
#define IPFIX_exportProtocolVersion_LEN                 sizeof(uint8_t)
#define IPFIX_exportTransportProtocol_LEN               sizeof(uint8_t)
#define IPFIX_collectorTransportPort_LEN                sizeof(uint16_t)
#define IPFIX_exporterTransportPort_LEN                 sizeof(uint16_t)
#define IPFIX_tcpSynTotalCount_LEN                      sizeof(uint64_t)
#define IPFIX_tcpFinTotalCount_LEN                      sizeof(uint64_t)
#define IPFIX_tcpRstTotalCount_LEN                      sizeof(uint64_t)
#define IPFIX_tcpPshTotalCount_LEN                      sizeof(uint64_t)
#define IPFIX_tcpAckTotalCount_LEN                      sizeof(uint64_t)
#define IPFIX_tcpUrgTotalCount_LEN                      sizeof(uint64_t)
#define IPFIX_ipTotalLength_LEN                         sizeof(uint64_t)
#define IPFIX_postNATSourceIPv4Address_LEN              sizeof(in_addr)
#define IPFIX_postNATDestinationIPv4Address_LEN         sizeof(in_addr)
#define IPFIX_postNAPTSourceTransportPort_LEN           sizeof(uint16_t)
#define IPFIX_postNAPTDestinationTransportPort_LEN      sizeof(uint16_t)
#define IPFIX_natOriginatingAddressRealm_LEN            sizeof(uint8_t)
#define IPFIX_natEvent_LEN                              sizeof(uint8_t)
#define IPFIX_initiatorOctets_LEN                       sizeof(uint64_t)
#define IPFIX_responderOctets_LEN                       sizeof(uint64_t)
#define IPFIX_firewallEvent_LEN                         sizeof(uint8_t)
#define IPFIX_ingressVRFID_LEN                          sizeof(uint32_t)
#define IPFIX_egressVRFID_LEN                           sizeof(uint32_t)
#define IPFIX_VRFname_LEN                               sizeof(string)
#define IPFIX_postMplsTopLabelExp_LEN                   sizeof(uint8_t)
#define IPFIX_tcpWindowScale_LEN                        sizeof(uint16_t)
#define IPFIX_biflowDirection_LEN                       sizeof(uint8_t)
#define IPFIX_ethernetHeaderLength_LEN                  sizeof(uint8_t)
#define IPFIX_ethernetPayloadLength_LEN                 sizeof(uint16_t)
#define IPFIX_ethernetTotalLength_LEN                   sizeof(uint16_t)
#define IPFIX_dot1qVlanId_LEN                           sizeof(uint16_t)
#define IPFIX_dot1qPriority_LEN                         sizeof(uint8_t)
#define IPFIX_dot1qCustomerVlanId_LEN                   sizeof(uint16_t)
#define IPFIX_dot1qCustomerPriority_LEN                 sizeof(uint8_t)
#define IPFIX_metroEvcId_LEN                            sizeof(string)
#define IPFIX_metroEvcType_LEN                          sizeof(uint8_t)
#define IPFIX_pseudoWireId_LEN                          sizeof(uint32_t)
#define IPFIX_pseudoWireType_LEN                        sizeof(uint16_t)
#define IPFIX_pseudoWireControlWord_LEN                 sizeof(uint32_t)
#define IPFIX_ingressPhysicalInterface_LEN              sizeof(uint32_t)
#define IPFIX_egressPhysicalInterface_LEN               sizeof(uint32_t)
#define IPFIX_postDot1qVlanId_LEN                       sizeof(uint16_t)
#define IPFIX_postDot1qCustomerVlanId_LEN               sizeof(uint16_t)
#define IPFIX_ethernetType_LEN                          sizeof(uint16_t)
#define IPFIX_postIpPrecedence_LEN                      sizeof(uint8_t)
#define IPFIX_collectionTimeMilliseconds_LEN            sizeof(dateTimeMilliseconds)
#define IPFIX_exportSctpStreamId_LEN                    sizeof(uint16_t)
#define IPFIX_maxExportSeconds_LEN                      sizeof(dateTimeSeconds)
#define IPFIX_maxFlowEndSeconds_LEN                     sizeof(dateTimeSeconds)
#define IPFIX_messageMD5Checksum_LEN                    sizeof(octetArray)
#define IPFIX_messageScope_LEN                          sizeof(uint8_t)
#define IPFIX_minExportSeconds_LEN                      sizeof(dateTimeSeconds)
#define IPFIX_minFlowStartSeconds_LEN                   sizeof(dateTimeSeconds)
#define IPFIX_opaqueOctets_LEN                          sizeof(octetArray)
#define IPFIX_sessionScope_LEN                          sizeof(uint8_t)
#define IPFIX_maxFlowEndMicroseconds_LEN                sizeof(dateTimeMicroseconds)
#define IPFIX_maxFlowEndMilliseconds_LEN                sizeof(dateTimeMilliseconds)
#define IPFIX_maxFlowEndNanoseconds_LEN                 sizeof(dateTimeNanoseconds)
#define IPFIX_minFlowStartMicroseconds_LEN              sizeof(dateTimeMicroseconds)
#define IPFIX_minFlowStartMilliseconds_LEN              sizeof(dateTimeMilliseconds)
#define IPFIX_minFlowStartNanoseconds_LEN               sizeof(dateTimeNanoseconds)
#define IPFIX_collectorCertificate_LEN                  sizeof(octetArray)
#define IPFIX_exporterCertificate_LEN                   sizeof(octetArray)
#define IPFIX_dataRecordsReliability_LEN                sizeof(boolean)
#define IPFIX_observationPointType_LEN                  sizeof(uint8_t)
#define IPFIX_newConnectionDeltaCount_LEN               sizeof(uint32_t)
#define IPFIX_connectionSumDurationSeconds_LEN          sizeof(uint64_t)
#define IPFIX_connectionTransactionId_LEN               sizeof(uint64_t)
#define IPFIX_postNATSourceIPv6Address_LEN              sizeof(in6_addr)
#define IPFIX_postNATDestinationIPv6Address_LEN         sizeof(in6_addr)
#define IPFIX_natPoolId_LEN                             sizeof(uint32_t)
#define IPFIX_natPoolName_LEN                           sizeof(string)
#define IPFIX_anonymizationFlags_LEN                    sizeof(uint16_t)
#define IPFIX_anonymizationTechnique_LEN                sizeof(uint16_t)
#define IPFIX_informationElementIndex_LEN               sizeof(uint16_t)
#define IPFIX_p2pTechnology_LEN                         sizeof(string)
#define IPFIX_tunnelTechnology_LEN                      sizeof(string)
#define IPFIX_encryptedTechnology_LEN                   sizeof(string)
#define IPFIX_basicList_LEN                             sizeof(basicList)
#define IPFIX_subTemplateList_LEN                       sizeof(subTemplateList)
#define IPFIX_subTemplateMultiList_LEN                  sizeof(subTemplateMultiList)
#define IPFIX_bgpValidityState_LEN                      sizeof(uint8_t)
#define IPFIX_IPSecSPI_LEN                              sizeof(uint32_t)
#define IPFIX_greKey_LEN                                sizeof(uint32_t)
#define IPFIX_natType_LEN                               sizeof(uint8_t)
#define IPFIX_initiatorPackets_LEN                      sizeof(uint64_t)
#define IPFIX_responderPackets_LEN                      sizeof(uint64_t)
#define IPFIX_observationDomainName_LEN                 sizeof(string)
#define IPFIX_selectionSequenceId_LEN                   sizeof(uint64_t)
#define IPFIX_selectorId_LEN                            sizeof(uint64_t)
#define IPFIX_informationElementId_LEN                  sizeof(uint16_t)
#define IPFIX_selectorAlgorithm_LEN                     sizeof(uint16_t)
#define IPFIX_samplingPacketInterval_LEN                sizeof(uint32_t)
#define IPFIX_samplingPacketSpace_LEN                   sizeof(uint32_t)
#define IPFIX_samplingTimeInterval_LEN                  sizeof(uint32_t)
#define IPFIX_samplingTimeSpace_LEN                     sizeof(uint32_t)
#define IPFIX_samplingSize_LEN                          sizeof(uint32_t)
#define IPFIX_samplingPopulation_LEN                    sizeof(uint32_t)
#define IPFIX_samplingProbability_LEN                   sizeof(float64)
#define IPFIX_dataLinkFrameSize_LEN                     sizeof(uint16_t)
#define IPFIX_ipHeaderPacketSection_LEN                 sizeof(octetArray)
#define IPFIX_ipPayloadPacketSection_LEN                sizeof(octetArray)
#define IPFIX_dataLinkFrameSection_LEN                  sizeof(octetArray)
#define IPFIX_mplsLabelStackSection_LEN                 sizeof(octetArray)
#define IPFIX_mplsPayloadPacketSection_LEN              sizeof(octetArray)
#define IPFIX_selectorIdTotalPktsObserved_LEN           sizeof(uint64_t)
#define IPFIX_selectorIdTotalPktsSelected_LEN           sizeof(uint64_t)
#define IPFIX_absoluteError_LEN                         sizeof(float64)
#define IPFIX_relativeError_LEN                         sizeof(float64)
#define IPFIX_observationTimeSeconds_LEN                sizeof(dateTimeSeconds)
#define IPFIX_observationTimeMilliseconds_LEN           sizeof(dateTimeMilliseconds)
#define IPFIX_observationTimeMicroseconds_LEN           sizeof(dateTimeMicroseconds)
#define IPFIX_observationTimeNanoseconds_LEN            sizeof(dateTimeNanoseconds)
#define IPFIX_digestHashValue_LEN                       sizeof(uint64_t)
#define IPFIX_hashIPPayloadOffset_LEN                   sizeof(uint64_t)
#define IPFIX_hashIPPayloadSize_LEN                     sizeof(uint64_t)
#define IPFIX_hashOutputRangeMin_LEN                    sizeof(uint64_t)
#define IPFIX_hashOutputRangeMax_LEN                    sizeof(uint64_t)
#define IPFIX_hashSelectedRangeMin_LEN                  sizeof(uint64_t)
#define IPFIX_hashSelectedRangeMax_LEN                  sizeof(uint64_t)
#define IPFIX_hashDigestOutput_LEN                      sizeof(boolean)
#define IPFIX_hashInitialiserValue_LEN                  sizeof(uint64_t)
#define IPFIX_selectorName_LEN                          sizeof(string)
#define IPFIX_upperCILimit_LEN                          sizeof(float64)
#define IPFIX_lowerCILimit_LEN                          sizeof(float64)
#define IPFIX_confidenceLevel_LEN                       sizeof(float64)
#define IPFIX_informationElementDataType_LEN            sizeof(uint8_t)
#define IPFIX_informationElementDescription_LEN         sizeof(string)
#define IPFIX_informationElementName_LEN                sizeof(string)
#define IPFIX_informationElementRangeBegin_LEN          sizeof(uint64_t)
#define IPFIX_informationElementRangeEnd_LEN            sizeof(uint64_t)
#define IPFIX_informationElementSemantics_LEN           sizeof(uint8_t)
#define IPFIX_informationElementUnits_LEN               sizeof(uint16_t)
#define IPFIX_privateEnterpriseNumber_LEN               sizeof(uint32_t)
#define IPFIX_virtualStationInterfaceId_LEN             sizeof(octetArray)
#define IPFIX_virtualStationInterfaceName_LEN           sizeof(string)
#define IPFIX_virtualStationUUID_LEN                    sizeof(octetArray)
#define IPFIX_virtualStationName_LEN                    sizeof(string)
#define IPFIX_layer2SegmentId_LEN                       sizeof(uint64_t)
#define IPFIX_layer2OctetDeltaCount_LEN                 sizeof(uint64_t)
#define IPFIX_layer2OctetTotalCount_LEN                 sizeof(uint64_t)
#define IPFIX_ingressUnicastPacketTotalCount_LEN        sizeof(uint64_t)
#define IPFIX_ingressMulticastPacketTotalCount_LEN      sizeof(uint64_t)
#define IPFIX_ingressBroadcastPacketTotalCount_LEN      sizeof(uint64_t)
#define IPFIX_egressUnicastPacketTotalCount_LEN         sizeof(uint64_t)
#define IPFIX_egressBroadcastPacketTotalCount_LEN       sizeof(uint64_t)
#define IPFIX_monitoringIntervalStartMilliSeconds_LEN   sizeof(dateTimeMilliseconds)
#define IPFIX_monitoringIntervalEndMilliSeconds_LEN     sizeof(dateTimeMilliseconds)
#define IPFIX_portRangeStart_LEN                        sizeof(uint16_t)
#define IPFIX_portRangeEnd_LEN                          sizeof(uint16_t)
#define IPFIX_portRangeStepSize_LEN                     sizeof(uint16_t)
#define IPFIX_portRangeNumPorts_LEN                     sizeof(uint16_t)
#define IPFIX_staMacAddress_LEN                         ETH_ALEN
#define IPFIX_staIPv4Address_LEN                        sizeof(in_addr)
#define IPFIX_wtpMacAddress_LEN                         ETH_ALEN
#define IPFIX_ingressInterfaceType_LEN                  sizeof(uint32_t)
#define IPFIX_egressInterfaceType_LEN                   sizeof(uint32_t)
#define IPFIX_rtpSequenceNumber_LEN                     sizeof(uint16_t)
#define IPFIX_userName_LEN                              sizeof(string)
#define IPFIX_applicationCategoryName_LEN               sizeof(string)
#define IPFIX_applicationSubCategoryName_LEN            sizeof(string)
#define IPFIX_applicationGroupName_LEN                  sizeof(string)
#define IPFIX_originalFlowsPresent_LEN                  sizeof(uint64_t)
#define IPFIX_originalFlowsInitiated_LEN                sizeof(uint64_t)
#define IPFIX_originalFlowsCompleted_LEN                sizeof(uint64_t)
#define IPFIX_distinctCountOfSourceIPAddress_LEN        sizeof(uint64_t)
#define IPFIX_distinctCountOfDestinationIPAddress_LEN   sizeof(uint64_t)
#define IPFIX_distinctCountOfSourceIPv4Address_LEN      sizeof(uint32_t)
#define IPFIX_distinctCountOfDestinationIPv4Address_LEN sizeof(uint32_t)
#define IPFIX_distinctCountOfSourceIPv6Address_LEN      sizeof(uint64_t)
#define IPFIX_distinctCountOfDestinationIPv6Address_LEN sizeof(uint64_t)
#define IPFIX_valueDistributionMethod_LEN               sizeof(uint8_t)
#define IPFIX_rfc3550JitterMilliseconds_LEN             sizeof(uint32_t)
#define IPFIX_rfc3550JitterMicroseconds_LEN             sizeof(uint32_t)
#define IPFIX_rfc3550JitterNanoseconds_LEN              sizeof(uint32_t)
#define IPFIX_dot1qDEI_LEN                              sizeof(boolean)
#define IPFIX_dot1qCustomerDEI_LEN                      sizeof(boolean)
#define IPFIX_flowSelectorAlgorithm_LEN                 sizeof(uint16_t)
#define IPFIX_flowSelectedOctetDeltaCount_LEN           sizeof(uint64_t)
#define IPFIX_flowSelectedPacketDeltaCount_LEN          sizeof(uint64_t)
#define IPFIX_flowSelectedFlowDeltaCount_LEN            sizeof(uint64_t)
#define IPFIX_selectorIDTotalFlowsObserved_LEN          sizeof(uint64_t)
#define IPFIX_selectorIDTotalFlowsSelected_LEN          sizeof(uint64_t)
#define IPFIX_samplingFlowInterval_LEN                  sizeof(uint64_t)
#define IPFIX_samplingFlowSpacing_LEN                   sizeof(uint64_t)
#define IPFIX_flowSamplingTimeInterval_LEN              sizeof(uint64_t)
#define IPFIX_flowSamplingTimeSpacing_LEN               sizeof(uint64_t)
#define IPFIX_hashFlowDomain_LEN                        sizeof(uint16_t)
#define IPFIX_transportOctetDeltaCount_LEN              sizeof(uint64_t)
#define IPFIX_transportPacketDeltaCount_LEN             sizeof(uint64_t)
#define IPFIX_originalExporterIPv4Address_LEN           sizeof(in_addr)
#define IPFIX_originalExporterIPv6Address_LEN           sizeof(in6_addr)
#define IPFIX_originalObservationDomainId_LEN           sizeof(uint32_t)
#define IPFIX_intermediateProcessId_LEN                 sizeof(uint32_t)
#define IPFIX_ignoredDataRecordTotalCount_LEN           sizeof(uint64_t)
#define IPFIX_dataLinkFrameType_LEN                     sizeof(uint16_t)
#define IPFIX_sectionOffset_LEN                         sizeof(uint16_t)
#define IPFIX_sectionExportedOctets_LEN                 sizeof(uint16_t)
#define IPFIX_dot1qServiceInstanceTag_LEN               sizeof(octetArray)
#define IPFIX_dot1qServiceInstanceId_LEN                sizeof(uint32_t)
#define IPFIX_dot1qServiceInstancePriority_LEN          sizeof(uint8_t)
#define IPFIX_dot1qCustomerSourceMacAddress_LEN         ETH_ALEN
#define IPFIX_dot1qCustomerDestinationMacAddress_LEN    ETH_ALEN
#define IPFIX_postLayer2OctetDeltaCount_LEN             sizeof(uint64_t)
#define IPFIX_postMCastLayer2OctetDeltaCount_LEN        sizeof(uint64_t)
#define IPFIX_postLayer2OctetTotalCount_LEN             sizeof(uint64_t)
#define IPFIX_postMCastLayer2OctetTotalCount_LEN        sizeof(uint64_t)
#define IPFIX_minimumLayer2TotalLength_LEN              sizeof(uint64_t)
#define IPFIX_maximumLayer2TotalLength_LEN              sizeof(uint64_t)
#define IPFIX_droppedLayer2OctetDeltaCount_LEN          sizeof(uint64_t)
#define IPFIX_droppedLayer2OctetTotalCount_LEN          sizeof(uint64_t)
#define IPFIX_ignoredLayer2OctetTotalCount_LEN          sizeof(uint64_t)
#define IPFIX_notSentLayer2OctetTotalCount_LEN          sizeof(uint64_t)
#define IPFIX_layer2OctetDeltaSumOfSquares_LEN          sizeof(uint64_t)
#define IPFIX_layer2OctetTotalSumOfSquares_LEN          sizeof(uint64_t)
#define IPFIX_layer2FrameDeltaCount_LEN                 sizeof(uint64_t)
#define IPFIX_layer2FrameTotalCount_LEN                 sizeof(uint64_t)
#define IPFIX_pseudoWireDestinationIPv4Address_LEN      sizeof(in_addr)
#define IPFIX_ignoredLayer2FrameTotalCount_LEN          sizeof(uint64_t)

// IPFIX header defines

#define IPFIX_VER       0x0700
#define IPFIX_TMPLT     0x0200
#define IPFIX_OPT_TMPLT 0x0300

#define IPFIX_OBS_DOMID 0x9a020000
#define IPFIX_TID       0x0001

// netflow IPFIX structures

typedef struct ipfixHdr_s {
	uint16_t version;
	uint16_t length;
	uint32_t exprtTime;
	uint32_t seqNum;
	uint32_t obsDomID;
} ipfixHdr_t;

#pragma pack(push, 1)
typedef struct ipfixT_s {
	uint16_t setID;
	uint16_t len;
	uint16_t tmpltID;
	uint16_t fieldCnt;
} ipfixT_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct ipfixData_s {
	uint64_t flowId;
	uint64_t flowKeyIndicator;
	uint32_t flowStartSeconds;
	uint32_t flowEndSeconds;
	//uint64_t flowStartMicroseconds;
	//uint64_t flowEndMicroseconds;
	uint32_t sourceIPv4Address;
	uint32_t destinationIPv4Address;
	uint16_t sourceTransportPort;
	uint16_t destinationTransportPort;
	uint8_t protocolIdentifier;
	uint8_t ipClassOfService;
	uint16_t tcpControlBits;
	uint64_t packetDeltaCount;
	uint64_t octetDeltaCount;
	uint64_t minimumIpTotalLength;
	uint64_t maximumIpTotalLength;
	uint32_t ipv4Options;
	uint32_t tcpOptions;
	//uint64_t flowKeyIndicator;
	//uint32_t mplsTopLabelExp;
	//uint32_t mplsLabelStackDepth;
	//uint32_t greKey;
	uint8_t minimumTTL;
	uint8_t maximumTTL;
	uint16_t vlanId;
} ipfixData_t;
#pragma pack(pop)

#endif // NETFLOW_IPFIX_H_
