#!/usr/bin/env bash

source "$(dirname "$0")/../../../scripts/t2utils.sh"

usage() {
    printf "Usage:\n"
    printf "    $SNAME [OPTION...] <malfile.txt>\n"
    printf "\nOptional arguments:\n"
    printf "    -h          display this help, then exit\n"
}

while [ $# -gt 0 ]; do
    case "$1" in
        -h|-\?|--help)
            usage
            exit 0
            ;;
        *)
            if [ ! -f "$1" ]; then
                abort_option_unknown "$1"
            fi
            INFILE="$1"
            ;;
    esac
    shift
done

if [ ! -f "$INFILE" ]; then
    abort_required_file
fi

cut -f 2 "$INFILE" | sort -u | $AWK -F"\t" '
    BEGIN { u = 0 }
    !/^#/ {
        printf "%s\t%d\n", $1, ++u
    }' > maltype.txt

$AWK -F'\t' '
    ARGIND == 1 {
        a[$1] = $2
        next
    }
    !/^#/ {
        printf "%s\t%d\t%s\n", $1, a[$2], $2
    }' maltype.txt "$INFILE" | LC_ALL=C sort -k 1,1 | uniq > maldm.txt
