#!/usr/bin/env bash
#
# Configuration file for icmpDecode
#
# Usage: ./t2plconf
#
# [Defining the configurations options]
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for TYPE 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for TYPE 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for TYPE 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - check: description
#       - radio: description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range: description ':' min ' ' max
#       - text : description

ITEMS=(
    ICMP_TC_MD radio ""
        "Type code representation; \
            0: Bitfield; \
            1: Explicit array of type code; \
            2: type code statistics"

    ICMP_NUM range "ICMP_TC_MD == 1" "Number of type and code info / flow: 0 255"

    ICMP_FDCORR check "" "Flow direction correction"
    ICMP_PARENT check "" "Try to link the parent flow"

    ICMP_STATFILE check "" "Print global ICMP statistics in a file"
    ICMP_SUFFIX text "ICMP_STATFILE == 1" "Suffix for output file"
)

# Source the main config file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
